locale: "fr-FR"
title: The Bootmaker home # Title of your site
url: "http://thebootmaker.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Comme à la maison. 

# Author details for the jekyll-seo-tag gem
author:
  name: P-A 
  email: pa.bouttier@me.com
  #twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
#social:
#name: Strata Reloaded Template
#links:
#- https://github.com/comfusion/strata-reloaded-jekyll-template

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - RSS
